### ISSUE TITLE
Investigate: Slowness on Applications List

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1444] opened 2022-11-17 21:45 UTC
Even though this isn't part of the **Approved: MVP** list prior to Angola's launch, just good to add here so we remember at some point it will require investigation and possibly some improvements (development).

[Updated 24th November 2022]
The slowness of the Applications list has a crucial impact on the usage of the App. After improvements were done to the Dashboard (that uses the same query) and indexes all over the relations on the Database has improved the performance. Although the list is still taking around 5-10 seconds to load on a powerful server and not many applications...

It's good to mention that the slowness on the Application's list is particularly observed by internal users, so external users aren't affect as much - but still a little slow to list the applications.

The source of the problem is known: 2 functions that are called for each application to deduce the latest actions available for assigner/reviewer which is computing the information live all of the time. 
The team has come up with a few options to improve this performance:

1. There might be a *little* bit more we can improve with indexing, but I doubt it would be enough.
2. Require re-thinking the application list functions, which will be a bigger job.
3. Tweaking Postgress to use RAM fully - I suspect it's not yet using in full
4. Try running App/Server not in a Docker container 

List of issues related
- [ ] #1393

**Comment by CarlosNZ** [comment] 2022-11-24 22:31
> 2 functions

There's a lot more than 2! Those functions each call other functions, which do their own queries. Basically, the number of queries required for each *row* of the list is crazy.

**Comment by CarlosNZ** [comment] 2022-11-30 03:58
Closing -- duplicate of https://github.com/openmsupply/conforma-server/issues/983 (I've linked to this issue from there, so we can easily access any additional info contained here)

**Closed by CarlosNZ** 2022-11-30 03:58 UTC
Labels: Bug: production, Customer: Angola, Customer: Fiji
