### ISSUE TITLE
Bug: Applicant going to their own Summary page after submission results in infinite re-direct

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1232] opened 2022-07-08 04:12 UTC
Keeps bouncing back and forth rapidly between the application home url and the /summary page

**Comment by CarlosNZ** [comment] 2022-07-08 04:54
Hey @fergus, this seems like something you might want to take a look at. Happy to help guide you in the right direction if you're a bit lost.

You'll want to start by looking at the re-direction logic in `ApplicationSummary.tsx`. The page is being redirected by ReactRouter based on the current application status, but somehow we've ended up with another re-direct somewhere else which is just sending it back here.

**Comment by fergie-nz** [comment] 2022-07-11 04:19
Hi Carl,

I'm unable to reproduce the error. Is there a specific application or database which is playing up?

**Comment by CarlosNZ** [comment] 2022-07-11 08:37
I *think* it happens for **completed** applications, not 100% sure. I'll check it tomorrow and let you know.

**Comment by CarlosNZ** [comment] 2022-07-11 21:40
Yeah, I can't seem to reproduce this now either. I'll keep an eye out and I'll be sure to take a snapshot if I see it again.

**Comment by nmadruga** [comment] 2022-08-24 04:08
I'll close this for now, since it hasn't been replicated. We have other issues to be looked at with more priority. Let's keep the ones that haven't happen again as closed. I think it's easier to track

**Comment by CarlosNZ** [comment] 2022-10-04 00:39
I'm seeing this again now. As an applicant, go to the list, and click on one of your own completed applications that has a "View" link. It'll go to the summary page and then bounce back and forth between that and something else (can't quite see). I think it's adding the query parameters and then removing them again, not 100% sure. 

I'll re-open this and have a quick look later on today.

**Comment by CarlosNZ** [comment] 2022-10-05 00:28
Here's a screen capture of the problem happening:

https://user-images.githubusercontent.com/5456533/193954281-ba83ec53-df75-420e-b98c-0ba022a96dfd.mov

**Closed** 2022-10-05 03:37 UTC
Labels: Bug: production, Phase 2
